services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: £U067qbAy3Q`
      ACCEPT_EULA: Y
    networks:
      sqlnet:
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "£U067qbAy3Q`", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
  sqlcmd:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlcmd
    depends_on:
      sqlserver:
        condition: service_healthy
    entrypoint: /bin/bash
    tty: true
    networks:
      - sqlnet

networks:
  sqlnet: